---
title: "FEMA_schools"
format: html
editor: visual
---

```{r, warning = F, message = F,  results='hide'}
# Load the libraries needed for the analysis
library(tidyverse)
library(sf)
library(terra)
library(dplyr)
library(spData)
library(spDataLarge)
library(ggplot2)
library(tmap)
library(RColorBrewer)
```

```{r}
# read in FEMA data for entire state
FEMA_state <- st_read("/capstone/casaschools/flooding/NFHL_06_20240401/NFHL_06_20240401.gdb",
                      layer = "S_FLD_HAZ_AR",
                      quiet = TRUE)
```

```{r}
# read in california schools data
schools <- st_read("/capstone/casaschools/schools_data/schools_buffer/",
                        quiet = TRUE)
```

```{r}
st_crs(FEMA_state) == st_crs(schools)

st_crs(schools)
st_crs(FEMA_state)

FEMA_state <- st_transform(FEMA_state, crs = st_crs(schools))

```

```{r}
#filter to high risk only
schools_high <- FEMA_state %>% 
  mutate(flood_risk = ifelse(str_detect(FLD_ZONE, "A"), "High Risk", NA))

schools_high <- schools_high %>% filter(flood_risk=="High Risk")

#unionize
#schools_high <- st_union(schools_high)

#st_write(schools_high, "/capstone/casaschools/fema-data/intermediate_layers/fema_high_union.shp")

#clip school buffers to flood intersections
FEMA_schools_high <- st_intersection(schools, schools_high)
```

```{r}
#find areas of FEMA areas in school intersected polygons
FEMA_schools_high$FEMA_area <- st_area(FEMA_schools_high)

#find area of school district boundaries
schools$area <- st_area(schools)

```

```{r}
#select neccessary columns
FEMA_schools_join <- FEMA_schools_high %>% 
  select(FedID, FEMA_area)
```

```{r}
# join high risk with schools to find percentage of area
join_flood_schools <- left_join(schools %>% as.data.frame(),
                       FEMA_schools_join %>% as.data.frame(),
                       by = "FedID", keep = FALSE, multiple = "first") %>%
  mutate(area = as.numeric(area), # convert areas to numeric, dropping the units
         FEMA_area = as.numeric(FEMA_area)) %>%
  mutate(FEMA_area = replace_na(FEMA_area, 0)) %>% # replace NAs with 0s
  mutate(FEMA_percent = (FEMA_area / area) * 100) %>% # calculate sea level rise inundation percentage
  st_sf(sf_column_name = "geometry.x")
```

```{r}
# select relevant information and export to server for hazard summary calculation
flooding_schools <- join_flood_schools %>% 
  select(CDSCode, SchoolName, FEMA_percent) %>% 
  st_drop_geometry()

write_csv(flooding_schools, "/capstone/casaschools/hazard_summary/individual_tables/flood_schools.csv")
```

### testing

```{r}
fema_high_union <- st_read("/capstone/casaschools/flooding/intermediate_layers/fema_high_union.shp", quiet = TRUE)

plot(fema_high_union)

fema_simple <- st_simplify(fema_high_union)


# selecting only necessary columns
fema_sub <- FEMA_state %>% 
  select(SHAPE, FLD_ZONE) %>% 
  st_as_sf()

# union
fema_test <- FEMA_state %>% 
  mutate(flood_risk = ifelse(str_detect(FLD_ZONE, "A"), "High Risk", NA))

# high risk subset
fema_test <- fema_test %>% filter(flood_risk=="High Risk") %>% 
  select(SHAPE, FLD_ZONE)

# 
fema_union <- fema_test %>%
  group_by(FLD_ZONE) %>%
  summarize(geometry = st_union(SHAPE), .groups = 'drop')
```

Make layers load faster by school buffers to

```{r}

```
