
```{r, warning = F, message = F,  results='hide'}
# Load the libraries needed for the analysis
library(tidyverse)
library(sf)
library(terra)
library(dplyr)
library(spData)
library(spDataLarge)
library(ggplot2)
library(tmap)
```


```{r}
CA_FEMA <- st_read("/capstone/casaschools/flooding/06111C_20240219/S_FLD_HAZ_AR.shp") 

#check class 
class(CA_FEMA)

#check columns 
head(CA_FEMA)

#see it plots for all CA
plot(CA_FEMA)

#CA_school_boundaries <- st_read("/Users/lianechen/Documents/5_MEDS/5_capstone/6_GitHub/data/California_School_District_Areas_2022-23/California_School_District_Areas_2022-23.shp") 

# read in california schools data
ca_districts <- st_read("/capstone/casaschools/schools_data/California_School_District_Areas_2022-23/",
                        quiet = TRUE)

st_crs(CA_FEMA) == st_crs(ca_districts)

st_crs(ca_districts)
st_crs(CA_FEMA)

CA_FEMA <- st_transform(CA_FEMA, crs = st_crs(ca_districts))
```

##Map flood hazards for Santa Paula Unified School District
```{r}
# Santa Paula Unified School District
head(ca_districts)

santa_paula <- ca_districts %>% filter(DistrictNa == "Santa Paula Unified") 

ggplot() +
  geom_sf(data = santa_paula)

```

```{r}
ggplot() +
  geom_sf(data = santa_paula, alpha = 1, color = "red") +
  geom_sf(data = CA_FEMA,aes(fill=FLD_ZONE), alpha = 0.5) +
  ggtitle("Severe Flood Hazard Areas in Ventura County") +
  scale_fill_brewer(name="Flood Zones") +
  theme_void()
```

```{r}
# Clip the FEMA to be within the Santa Paula District
sp_district <- st_intersection(CA_FEMA, santa_paula)


# Filter background to be multiple nearby districts
ventura <- ca_districts %>% 
  filter(CountyName == "Ventura")


ggplot() +
  geom_sf(data = ventura, fill = "white") +
geom_sf(data = sp_district, aes(fill = FLD_ZONE), alpha = 0.5) +
  theme_void()


tmap_mode("view")

tm_shape(ventura) +
  tm_polygons(fill = "white") +
  tm_shape(data = sp_district) +
  tm_polygons("FLD_ZONE")


tm_shape(sp_district) +
  tm_polygons(data = ventura) +
  tm_polygons("FLD_ZONE")

```


```{r}
# Final Map on Presentation-------
## Group the A's as High Risk ----


sp_district_1 <- sp_district %>% 
  mutate("Flood Risk" = ifelse(str_detect(FLD_ZONE, "A"), "High Risk",
                       ifelse(str_detect(FLD_ZONE, "D"),"Undetermined",
                              "Moderate to Low Risk Area")))


custom_palette <- c("High Risk" = "#BD0026", "Undetermined" = "lightblue", "Moderate to Low Risk Area" = "#FECC5C")


tm_shape(sp_district_1) +
  tm_polygons("Flood Risk", palette = custom_palette)
  


```


##Map flooding hazards for all CA school districts
```{r}
ggplot() +
  geom_sf(data = ca_districts)

ggplot() +
  geom_sf(data = ca_districts, alpha = 1, color = "red") +
  geom_sf(data = CA_FEMA_districts,aes(fill=FLD_ZONE), alpha = 0.5) +
  ggtitle("Severe Flood Hazard Areas in California") +
  scale_fill_brewer(name="Flood Zones") +
  theme_void()

# Clip the FEMA to be within CA
CA_FEMA_districts <- st_intersection(ca_districts, CA_FEMA)

head(CA_FEMA_districts)

ggplot() +
geom_sf(data = CA_FEMA_districts, aes(fill = FLD_ZONE), alpha = 0.5) +
  theme_void()


tmap_mode("view")

tm_shape(CA_FEMA_districts) +
  tm_polygons(fill = "white") +
  #tm_shape(data = CA_FEMA_districts) + #ERROR: not sure why this keeps going back to Ventura
  tm_polygons("FLD_ZONE")


```

```{r}
## Group the A's as High Risk ----

CA_districts_1 <- CA_districts %>% 
  mutate("Flood Risk" = ifelse(str_detect(FLD_ZONE, "A"), "High Risk",
                       ifelse(str_detect(FLD_ZONE, "D"),"Undetermined",
                              "Moderate to Low Risk Area")))


custom_palette <- c("High Risk" = "#BD0026", "Undetermined" = "lightblue", "Moderate to Low Risk Area" = "#FECC5C")


tm_shape(CA_districts_1) +
  tm_polygons("Flood Risk", palette = custom_palette)
```

```{r}
plot(CA_FEMA)
```

