
```{r, warning = F, message = F,  results='hide'}
# Load the libraries needed for the analysis
library(tidyverse)
library(sf)
library(terra)
library(dplyr)
library(spData)
library(spDataLarge)
library(ggplot2)
library(tmap)
library(RColorBrewer)

```


```{r}
FEMA_state <- st_read("/capstone/casaschools/flooding/NFHL_06_20240401/NFHL_06_20240401.gdb")

#st_layers("/capstone/casaschools/flooding/NFHL_06_20240307/NFHL_06_20240307.gdb")
```

```{r}

FEMA_state <- st_read("/capstone/casaschools/flooding/NFHL_06_20240401/NFHL_06_20240401.gdb", layer = "S_FLD_HAZ_AR")

plot(FEMA_state)
```






```{r}
ggplot(FEMA_state) +
  geom_sf(aes(fill=FLD_ZONE), alpha = 0.5) +
  ggtitle("Severe Flood Hazard Areas in California") +
  scale_fill_brewer(name="Flood Zones") +
  theme(panel.background = element_blank())
```

```{r}
# read in california schools data
ca_districts <- st_read("/capstone/casaschools/schools_data/California_School_District_Areas_2022-23/",
                        quiet = TRUE)

st_crs(FEMA_state) == st_crs(ca_districts)

st_crs(ca_districts)
st_crs(FEMA_state)

FEMA_state <- st_transform(FEMA_state, crs = st_crs(ca_districts))
```


##Map flood hazards for CA Unified School Districts
```{r}
# CA Unified School District
head(ca_districts)

plot(ca_districts)

# generate a unique ID for each school district
#ca_districts$DistrictNa <- seq(1:nrow(ca_districts))

ca_districts <- ca_districts["DistrictNa"]
head(ca_districts)

ggplot() +
  geom_sf(data = ca_districts)


ggplot() +
  geom_sf(data = ca_districts) +
  geom_sf(data = FEMA_state, aes(fill=FLD_ZONE)) +
  scale_fill_brewer(palette = "Blues")
  
```

#look into each category, only keep relevant zones
#We do this in the flooding_mapping


