---
title: "joining data"
format: html
---

```{r}
#Load in ibraries
library(tidyverse)
library(sf)
```

# Data Cleaning

```{r}
options(scipen = 999)

current85 <- read.csv("/capstone/casaschools/precipitation/curcentury85.csv")
 mid85 <- read.csv("/capstone/casaschools/precipitation/midcentury85.csv")
 #historic <- read.csv("/capstone/casaschools/precipitation/historic85.csv")
 
 #add in century column
 
 current85 <- current85 %>%mutate(century = "Current")
 
 mid85 <- mid85 %>%mutate(century = "Mid")
 
 #historic <- historic %>%  mutate(century = "Historic")
 
 #rename total columns
 
 current85 <- current85 %>%rename(total = total_06_34)
 
 mid85 <- mid85 %>%rename(total = total_35_64)
 
 #historic <- historic %>%rename(total = total_00_06)
 

 # century_totals_combined <- rbind(mid85, current85, historic)
 
 century_totals_combined <- rbind(mid85, current85)
 
 century_totals_combined <- century_totals_combined[, -1]

 #write.csv(century_totals_combined, "/capstone/casaschools/precipitation/century_totals_combined.csv")
 #write.csv(century_totals_combined, "/capstone/casaschools/shiny_dashboard/data/precipitation/century_totals_combined.csv")

```

```{r}

 options(scipen = 999)

 current85_year <- read.csv("/capstone/casaschools/precipitation/curcentury85_year.csv")
 mid85_year <- read.csv("/capstone/casaschools/precipitation/midcentury85_year.csv")
 #historic_year <- read.csv("/capstone/casaschools/precipitation/historic85_year.csv")
 
 current85_year <- current85_year %>%
   mutate(century = "Current")
 
 mid85_year <- mid85_year %>%
   mutate(century = "Mid")
 
 #historic_year <- historic_year %>% 
   #mutate(century = "Historic")
 #year_totals_combined <- rbind(mid85_year, current85_year, historic_year)
 
 year_totals_combined <- rbind(mid85_year, current85_year)
 
 year_totals_combined <- year_totals_combined[, -1]

#write.csv( year_totals_combined, "/capstone/casaschools/precipitation/year_totals_combined.csv")
# write.csv( year_totals_combined, "/capstone/casaschools/shiny_dashboard/data/precipitation/year_totals_combined.csv")
 
```

# Combining rcp4.5 scenarios

```{r}
options(scipen = 999)

current45 <- read.csv("/capstone/casaschools/precipitation/curcentury45.csv")
 mid45 <- read.csv("/capstone/casaschools/precipitation/midcentury45.csv")
 
 #add in century column
 
 current45 <- current45 %>%mutate(century = "Current")
 
 mid45 <- mid45 %>%mutate(century = "Mid")

 
 #rename total columns
 
 current45 <- current45 %>%rename(total = total_35_64)
 
 mid45 <- mid45 %>%rename(total = total_35_64)

 

 century_totals_combined45 <- rbind(mid45, current45)
 
 century_totals_combined45 <- century_totals_combined45[, -1]

 # write.csv(century_totals_combined45, "/capstone/casaschools/precipitation/century_totals_combined45.csv")
 # write.csv(century_totals_combined45, "/capstone/casaschools/shiny_dashboard/data/precipitation/century_totals_combined45.csv")
 
```

```{r}
 options(scipen = 999)

 current45_year <- read.csv("/capstone/casaschools/precipitation/curcentury45_year.csv")
 mid45_year <- read.csv("/capstone/casaschools/precipitation/midcentury45_year.csv")
 
 current45_year <- current45_year %>%
   mutate(century = "Current")
 
 mid45_year <- mid45_year %>%
   mutate(century = "Mid")

 year_totals_combined45 <- rbind(mid45_year, current45_year)
 
 year_totals_combined45 <- year_totals_combined45[, -1]

 # write.csv(year_totals_combined45, "/capstone/casaschools/precipitation/year_totals_combined45.csv")
 # write.csv(year_totals_combined45, "/capstone/casaschools/shiny_dashboard/data/precipitation/year_totals_combined45.csv")
 
```

# Join Scenarios

```{r}
century_totals_combined <- read.csv("/capstone/casaschools/precipitation/century_totals_combined.csv")

century_totals_combined45 <- read.csv("/capstone/casaschools/precipitation/century_totals_combined45.csv")

century_totals_combined <- century_totals_combined[, -1]
century_totals_combined45 <- century_totals_combined45[, -1]

century_totals_combined <- century_totals_combined %>% 
  mutate(scenario = "High Emissions")

century_totals_combined45 <- century_totals_combined45 %>% 
  mutate(scenario = "Low Emissions")

century_all <- rbind(century_totals_combined, century_totals_combined45)

#  write.csv(century_all, "/capstone/casaschools/precipitation/century_all.csv")
# write.csv(century_all, "/capstone/casaschools/shiny_dashboard/data/precipitation/century_all.csv")
#  
```

```{r}
year_totals_combined <- read.csv("/capstone/casaschools/precipitation/year_totals_combined.csv")

year_totals_combined45 <- read.csv("/capstone/casaschools/precipitation/year_totals_combined45.csv")

year_totals_combined <- year_totals_combined[, -1]
year_totals_combined45 <- year_totals_combined45[, -1]

# total days for RCP 8.5
year_totals_combined <- year_totals_combined %>% 
  mutate(scenario = "High Emissions")

# total days for RCP 4.5
year_totals_combined45 <- year_totals_combined45 %>% 
  mutate(scenario = "Low Emissions")

# bind high emissions and low emissions scenarios
years_all <- rbind(year_totals_combined, year_totals_combined45)
```

Each school has a unique 14 digit associated CDSCode. When working with the California_Schools_2022-23 dataset the CDSCode loses its initial 0. To prepare the extreme heat data to be joined with the rest of the hazards this missing 0 needs to be added back.

```{r}
#add back in zeros
years_all_zeros <- years_all %>%
  group_by(CDSCode, year, total, century, scenario) %>%
  summarise(total = sum(total)) %>%
  mutate(CDSCode = as.character(CDSCode),
         count = nchar(CDSCode),
         # some rows are missing 0's in front
         CDSCode = ifelse(count == 13, paste0("0", CDSCode),
                              CDSCode))

# add back in zeros for the RCP 8.5 data for use in the hazard summary calculation
rcp85_zeros <- year_totals_combined %>% 
  group_by(CDSCode, year, total, century, scenario) %>% 
  summarise(total = sum(total)) %>% 
  mutate(CDSCode = as.character(CDSCode),
         count = nchar(CDSCode),
         # some rows are missing 0's in front
         CDSCode = ifelse(count == 13, paste0("0", CDSCode),
                              CDSCode))

#write.csv(years_all, "/capstone/casaschools/precipitation/years_all.csv")

# write.csv(years_all_zeros, "/capstone/casaschools/precipitation/years_all_zeros.csv")
# 
# write.csv(years_all_zeros, "/capstone/casaschools/shiny_dashboard/data/precipitation/years_all_zeros.csv")
```

# Data preparation for dashboard

```{r}
precip <- read.csv("/capstone/casaschools/shiny_dashboard/data/precipitation/years_all_zeros.csv")

# Change the scenario names
precip <- precip %>% mutate(scenario = ifelse(scenario == "High Emissions","High greenhouse gas emissions","Reduced greenhouse gas emissions"))

# add zero
precip <- precip %>% mutate(CDSCode_old = as.character(CDSCode),
         # Count how many characters
         count = nchar(CDSCode),
         # If 13 add a 0 in front
         CDSCode = ifelse(count == 13, paste0("0",CDSCode_old),
                          CDSCode_old)) %>% 
  select(-c(CDSCode_old, count, X)) %>% 
  filter(year > 2005)

# merge with school data
school_points <- st_read("/capstone/casaschools/schools_data/California_Schools_2022-23/California_Schools_2022-23.shp") %>%
  st_drop_geometry() %>% 
  filter(Status == "Active") %>% 
  select(c(CDSCode, City, DistrictNa, SchoolName))

# Merge data 
extreme_precip <- left_join(precip,school_points, by = "CDSCode")

# export 

#write.csv(extreme_precip, "/capstone/casaschools/shiny_dashboard/data/precipitation/extreme_precipitation.csv")

test <- read.csv("/capstone/casaschools/shiny_dashboard/data/precipitation/extreme_precipitation.csv")

```

# RCP 8.5 2030 - 2035 for hazard summary

```{r}
# subset for years 2030-2035
year85_sum <- subset(rcp85_zeros, year %in% c(2030, 2031, 2032, 2033, 2034, 2035))

# only select CDSCode, total, and year columns
year85_sum <- year85_sum[, -c(4:6)]

year85_sum

# group by CDSCcode and sum the total number of extreme precip days over the range of years
schools_extreme_precip <- year_sum %>% 
  group_by(CDSCode) %>% 
  summarise(total_days = sum(total)) %>% 
  mutate(total_days = round(total_days,digits = 0))

schools_extreme_precip

# write results to the server
#write.csv(schools_extreme_precip, "/capstone/casaschools/precipitation/schools_extreme_precip.csv")

#write.csv(schools_extreme_precip, "/capstone/casaschools/hazard_summary/individual_tables/schools_extreme_precip.csv")
```
