---
title: "Accessing Extreme Precipitation Days for all Schools RCP 4.5"
format: html
author: "CASAschools Team"
---

```{r}
# Libraries
library(dplyr)
library(tidyr)
library(sf)
library(lubridate)
library(caladaptr)
library(units)
library(tidyverse)
```

```{r}
# Load school point data
school_points <- st_read("/capstone/casaschools/schools_data/California_Schools_2022-23/California_Schools_2022-23.shp")
```

```{r}
# Filter to schools are active and remove unnecessary columns
school_points <- school_points %>% filter(Status == "Active") %>% 
  select(c(CDSCode))

```

```{r}
# Import LOCA grid 
locagrid_sf <- ca_locagrid_geom()

# Check CRS of both data
st_crs(school_points) == st_crs(locagrid_sf)

# Transform school points to LOCA CRS
school_points <- st_transform(school_points, crs = st_crs(locagrid_sf))

# Spatially join points and grid
ca_schools_loca_sf <- school_points %>% st_join(locagrid_sf) 
ca_schools_loca_sf %>% st_drop_geometry()
```


```{r}
# Unique ID values
# we only have to query 1,619 school points
loca_ids_schools <- ca_schools_loca_sf %>% pull(id) %>% unique()


# Create a point layer for the 1,619 LOCA grid cells that contain schools
loca_ctr_sf <- locagrid_sf %>%
  filter(id %in% loca_ids_schools) %>%
  st_centroid()


# API request 
locaschl_et_cap <- ca_loc_sf(loc = loca_ctr_sf, idfld = "id") %>%
  # CanESM2, CNRM-CM5, HadGEM2-ES, MIROC5
  ca_gcm(gcms[1:4]) %>%
  ca_scenario(c("rcp45")) %>%
  ca_cvar("pr") %>%
  ca_period("day") %>%
  # Mid Century 
  ca_years(start = 2035, end = 2064)

# Check if request has no erros
locaschl_et_cap %>% ca_preflight()

head(locaschl_et_cap)
```


```{r}
#Next, we fetch the data. Because this is still a lot of locations, we’ll use ca_getvals_db() to save it in a database:
data_dir_precip_mid45 <- tools::R_user_dir("pr_mid_45", which = "data")
schools_dir_precip_mid45 <- file.path(data_dir_precip_mid45, "schools_pr_mid45") %>% normalizePath(mustWork = FALSE)
if (!file.exists(schools_dir_precip_mid45)) dir.create(schools_dir_precip_mid45, recursive = TRUE)

## Define a new SQLite file name
locaschl_fn <- file.path(schools_dir_precip_mid45, "loca_schl.sqlite") %>% normalizePath(mustWork = FALSE)


## Fetch data
locaschl_et_rtbl <- locaschl_et_cap %>%
  ca_getvals_db(db_fn = locaschl_fn, db_tbl = "locaschl_et", new_recs_only = TRUE, quiet = TRUE)


head(locaschl_et_rtbl)
```


```{r}
# Transform dataset 
locaschl_et_rtbl_1 <- locaschl_et_rtbl %>% 
  mutate(month = lubridate::month(dt),
         year = lubridate::year(dt),
         val = as.numeric(val))

# Set threshold determined in 'caladapt_precip_r.qmd' and calculate days over
locaschl_et_rtbl_1 <- locaschl_et_rtbl_1 %>%
   mutate(threshold = ifelse(val > 0.000216, 1, 0)) %>%
   # Find total number of days by month and year
   group_by(id, month, year) %>%
   summarise(count = sum(threshold))

# # View results
head(locaschl_et_rtbl_1)
```


```{r}
# # Find average monthly yearly days above threshold for 4 GCM's
 locaschl_et_rtbl_2 <- locaschl_et_rtbl_1 %>% 
   mutate(average = count/4)

# Rejoin with school points + LOCA id
 ca_schools_et_sf <- ca_schools_loca_sf %>%  
   left_join(locaschl_et_rtbl_2, by = "id", copy = TRUE) 

 head(ca_schools_et_sf)
```


```{r}
# Find yearly extreme precipitation
 ca_schools_et_year <- ca_schools_et_sf %>% 
   group_by(CDSCode, year) %>% 
   summarise(total = sum(count))
#   
 # Find sum total of extreme precipitation days across 1,0008 schools from 2035-2064
 ca_schools <- ca_schools_et_year %>% 
   group_by(CDSCode) %>% 
   summarise(total_35_64 = sum(total)) %>% 
   mutate(total_35_64 = round(total_35_64,digits = 0))
```


```{r}
# Export total extreme precipitation days per year

write.csv(ca_schools, "/capstone/casaschools/precipitation/midcentury4.5_precip_sum.csv")

write.csv(ca_schools, "precipitation/midcentury4.5_precip_sum.csv")

write.csv(ca_schools_et_year, "/capstone/casaschools/precipitation/midcentury4.5_precip_yeartotals.csv")

write.csv(ca_schools_et_year, "precipitation/midcentury4.5_precip_yeartotals.csv")

```

# 2006 to 2034

```{r}
# Import LOCA grid 
locagrid_sf <- ca_locagrid_geom()

# Check CRS of both data
st_crs(school_points) == st_crs(locagrid_sf)

# Transform school points to LOCA CRS
school_points <- st_transform(school_points, crs = st_crs(locagrid_sf))

# Spatially join points and grid
ca_schools_loca_sf <- school_points %>% st_join(locagrid_sf) 
ca_schools_loca_sf %>% st_drop_geometry()
```


```{r}
# Unique ID values
# we only have to query 1,619 school points
loca_ids_schools <- ca_schools_loca_sf %>% pull(id) %>% unique()


# Create a point layer for the 1,619 LOCA grid cells that contain schools
loca_ctr_sf <- locagrid_sf %>%
  filter(id %in% loca_ids_schools) %>%
  st_centroid()


# API request 
locaschl_et_cap <- ca_loc_sf(loc = loca_ctr_sf, idfld = "id") %>%
  # CanESM2, CNRM-CM5, HadGEM2-ES, MIROC5
  ca_gcm(gcms[1:4]) %>%
  ca_scenario(c("rcp45")) %>%
  ca_cvar("pr") %>%
  ca_period("day") %>%
  # Mid Century 
  ca_years(start = 2006, end = 2034)

# Check if request has no erros
locaschl_et_cap %>% ca_preflight()

head(locaschl_et_cap)
```


```{r}
#Next, we fetch the data. Because this is still a lot of locations, we’ll use ca_getvals_db() to save it in a database:
data_dir_precip_cur45 <- tools::R_user_dir("pr_cur_45", which = "data")
schools_dir_precip_cur45 <- file.path(data_dir_precip_cur45, "schools_pr_cur45") %>% normalizePath(mustWork = FALSE)
if (!file.exists(schools_dir_precip_cur45)) dir.create(schools_dir_precip_cur45, recursive = TRUE)

## Define a new SQLite file name
locaschl_fn <- file.path(schools_dir_precip_cur45, "loca_schl.sqlite") %>% normalizePath(mustWork = FALSE)


## Fetch data
locaschl_et_rtbl <- locaschl_et_cap %>%
  ca_getvals_db(db_fn = locaschl_fn, db_tbl = "locaschl_et", new_recs_only = TRUE, quiet = TRUE)

head(locaschl_et_rtbl)
```


```{r}
# Transform dataset 
locaschl_et_rtbl_1 <- locaschl_et_rtbl %>% 
  mutate(month = lubridate::month(dt),
         year = lubridate::year(dt),
         val = as.numeric(val))

# Set threshold determined in 'caladapt_precip_r.qmd' and calculate days over
locaschl_et_rtbl_1 <- locaschl_et_rtbl_1 %>%
   mutate(threshold = ifelse(val > 0.000216, 1, 0)) %>%
   # Find total number of days by month and year
   group_by(id, month, year) %>%
   summarise(count = sum(threshold))
# 
# # View results
 head(locaschl_et_rtbl_1)
```


```{r}
# # Find average monthly yearly days above threshold for 4 GCM's
 locaschl_et_rtbl_2 <- locaschl_et_rtbl_1 %>% 
   mutate(average = count/4)

# Rejoin with school points + LOCA id
 ca_schools_et_sf <- ca_schools_loca_sf %>%  
   left_join(locaschl_et_rtbl_2, by = "id", copy = TRUE) 

head(ca_schools_et_sf)
```


```{r}
# Find yearly extreme precipitation
 ca_schools_et_year <- ca_schools_et_sf %>% 
   group_by(CDSCode, year) %>% 
   summarise(total = sum(count))
#   
 # Find sum total of extreme precipitation days across 1,0008 schools from 2035-2064
 ca_schools <- ca_schools_et_year %>% 
   group_by(CDSCode) %>% 
   summarise(total_35_64 = sum(total)) %>% 
   mutate(total_35_64 = round(total_35_64,digits = 0))
```


```{r}
# Export total extreme precipitation days per year
write.csv(ca_schools, "/capstone/casaschools/precipitation/currentcent4.5_precip_sum.csv")

write.csv(ca_schools, "precipitation/currentcent4.5_precip_sum.csv")

write.csv(ca_schools_et_year, "/capstone/casaschools/precipitation/currentcent4.5_precip_yeartotals.csv")

write.csv(ca_schools_et_year, "precipitation/currentcent4.5_precip_yeartotals.csv")
```


# Join Data
```{r}
options(scipen = 999)


precip_00_06 <- read.csv("/capstone/casaschools/precipitation/hist8.5_precip_yeartotals.csv")


precip_rcp45_2006_2034 <- read.csv("/capstone/casaschools/precipitation/currentcent4.5_precip_yeartotals.csv")

precip_rcp45_2035_2064 <- read.csv("/capstone/casaschools/precipitation/midcentury4.5_precip_yeartotals.csv")


## Combine to make rcp45 2000-2064
precip_rcp45_2000_2064 <- rbind(precip_00_06, precip_rcp45_2006_2034, 
                              precip_rcp45_2035_2064)

precip_rcp45_2000_2064 <- precip_rcp45_2000_2064

### export csv to shinydashboard data
write.csv(precip_rcp45_2000_2064, "/capstone/casaschools/shiny_dashboard/data/precipitation/precip_rcp45_2000_2064.csv")

# Jrename columns
precip_rcp45_2000_2064 <- precip_rcp45_2000_2064 %>% 
  rename(
    CDSCode = X,
year = CDSCode,
total = year,
lat = total,
long = geometry
    )

precip_rcp85_2006_2064 <- precip_rcp85_2006_2064 %>% rename(
    CDSCode = X,
year = CDSCode,
total = year,
lat = total,
long = geometry
    )

```

```{r}
# extreme precip plot
dos_pueblos <- precip_rcp45_2000_2064 %>% filter(CDSCode == 42767864231726)



dos_pueblos$scenario <- 'intermediate scenario'

dos_pueblos85 <- precip_rcp85_2006_2064 %>% filter(CDSCode == 42767864231726)

dos_pueblos85$scenario <- 'business as usual'

dos_combined <- rbind(dos_pueblos, dos_pueblos85)

ggplot(dos_combined, aes(year, total)) + geom_line(aes(color = scenario)) + theme_minimal() + labs(x = "Year", y = "Number of Extreme Precipitation Days")

ggplot(data = sac_tasmax_tbl2, 
       aes(x = as.Date(dt), y = as.numeric(temp_f))) +
  geom_line(aes(color=gcm)) +
  facet_grid(scenario ~ .) +
  labs(title = "Annual Average Maximum Daily Temperature for Sacramento", x = "year", y = "temp (F)")

```

