---
title: "caladapt-r"
format: html
---

```{r}
# Install caladaptr
#devtools::install_github("ucanr-igis/caladaptr")

# Libraries
library(devtools)
library(caladaptr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)
library(sf)
library(rlist)
```

## Request daily maximum temperature for California school districts

```{r}
# Import school bounds
schools_bounds <- st_read("/capstone/casaschools/schools_data/schools_intersect/schools_intersect_bounds.shp") %>% 
  # Elementary school boundaries covers the same boundary areas as high schools
  # Reduce repition include only elementary and unified
  filter(DistrictTy %in% c("Elementary","Unified"))


schools_bounds <- st_make_valid(schools_bounds)

#plot(schools_bounds$geometry)

# Empty data frame
percentile <- data.frame()

# Loop across all school districts
for (name in schools_bounds$DistrictNa) {
  
  # Iterate through individual rows at a time
  df <- schools_bounds %>% 
    filter(DistrictNa ==  name)
  
  tryCatch({
    # API request
    request <- ca_loc_sf(loc = df, idfld = "CDSCode") %>% 
      ca_cvar(cvar = "tasmax") %>% 
      # Historic dataset
      ca_livneh(TRUE) %>% 
      ca_period("day")  %>% 
      ca_years(start = 1961, end = 1990)
    
    school_data <- request %>% 
      # Get values from request
      ca_getvals_tbl(quiet = TRUE) %>% 
      mutate(val = as.numeric(val)) %>%
      # Calculate 98th percentile for each district historic data
      summarize(percentile_98 = quantile(val, probs = 0.98))
    
    school_data$DistrictNa <- name
    
    percentile <- rbind(percentile, school_data)
  }, error = function(e) {
    cat("Error occurred for district:", name, "\n")
    # Print school districts API has difficulty with
    cat("Skipping this district.\n")
    
    
  })
}



```

## Working with Errors

```{r}
## By Census tracts

tracts <- ca_aoipreset_geom("counties")

schools_ers <- c("Del Norte County Unified","Big Sur Unified", 
                 "Cabrillo Unified", "South San Francisco Unified",
                 "Belmont-Redwood Shores Elementary",
                 "San Bruno Park Elementary", "San Mateo-Foster City",
                 "Horicon Elementary") 


error_bounds <- schools_bounds %>% 
  filter(DistrictNa %in% c(schools_ers))

error_bounds <- st_make_valid(error_bounds)



tracts_in_school <- st_intersection(tracts, error_bounds) %>% 
  select(c("CDCode","DistrictNa"))



data_df <- tracts_in_school %>%
  st_cast("POLYGON") %>%
  group_by(DistrictNa) %>%
  summarise(geometry = st_union(geom)) %>%
  st_sf()




```


```{r}
# Empty data frame
percentile_2 <- data.frame()

# Loop across all school districts
for (name in data_df$DistrictNa) {
  
  # Iterate through individual rows at a time
  df <- data_df %>% 
    filter(DistrictNa ==  name)
  
  tryCatch({
    # API request
    request <- ca_loc_sf(loc = df, idfld = "DistrictNa") %>% 
      ca_cvar(cvar = "tasmax") %>% 
      # Historic dataset
      ca_livneh(TRUE) %>% 
      ca_period("day")  %>% 
      ca_years(start = 1961, end = 1990)
    
    data_2 <- request %>% 
      # Get values from request
      ca_getvals_tbl(quiet = TRUE) %>% 
      mutate(val = as.numeric(val)) %>%
      # Calculate 98th percentile for each district historic data
      summarize(percentile_98 = quantile(val, probs = 0.98))
    
    data_2$DistrictNa <- name
    
    percentile_2 <- rbind(percentile_2, data_2)
  }, error = function(e) {
    cat("Error occurred for district:", name, "\n")
    # Print school districts API has difficulty with
    cat("Skipping this district.\n")
    
    
  })
}



```


```{r}
# Del Monte 
big_sur <- tracts_in_school %>% 
  filter(DistrictNa == "Del Monte") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>% 
  mutate("DistrictNa" = "Big Sur Unified")
  




request_trial <- ca_loc_sf(loc = big_sur, idfld = "DistrictNa") %>%
      ca_cvar(cvar = "tasmax") %>%
      # Historic dataset
      ca_livneh(TRUE) %>%
      ca_period("day")  %>%
      ca_years(start = 1961, end = 1990) %>% 
  ca_options(spatial_ag = "max")
    
plot(request_trial)

request_trial %>% ca_preflight()


trial_2 <- request_trial %>%
  #Get values from request
  ca_getvals_tbl(quiet = TRUE) %>%
  mutate(val = as.numeric(val)) %>%
  # Calculate 98th percentile for each district historic data
  summarize(percentile_98 = quantile(val, probs = 0.98))


```


```{r}
# Big Sur
big_sur <- tracts_in_school %>% 
  filter(DistrictNa == "Big Sur Unified") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>%  
  mutate("DistrictNa" = "Big Sur Unified")
  
# Cabrillo Unified
cabrillo <- tracts_in_school %>% 
  filter(DistrictNa == "Cabrillo Unified") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>% 
  mutate("DistrictNa" = "Cabrillo Unified")

# South San Francisco Unified
south_san_fran <- tracts_in_school %>% 
  filter(DistrictNa == "South San Francisco Unified") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>% 
  mutate("DistrictNa" = "South San Francisco Unified")

# Belmont-Redwood Shores Elementary
bel_mont <- tracts_in_school %>% 
  filter(DistrictNa == "Belmont-Redwood Shores Elementary") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>% 
  mutate("DistrictNa" = "Belmont-Redwood Shores Elementary")

# San Bruno Park Elementary
san_bruno <- tracts_in_school %>% 
  filter(DistrictNa == "San Bruno Park Elementary") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>% 
  mutate("DistrictNa" = "San Bruno Park Elementary")

# San Mateo-Foster City
san_mateo <- tracts_in_school %>% 
  filter(DistrictNa == "San Mateo-Foster City") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>% 
  mutate("DistrictNa" = "San Mateo-Foster City")

# Horicon Elementary
horicon <- tracts_in_school %>% 
  filter(DistrictNa == "Horicon Elementary") %>% 
  st_cast(.,"POLYGON") %>%
  st_union() %>% 
  st_sf() %>% 
  mutate("DistrictNa" = "Horicon Elementary")


data_df <- tracts_in_school %>%
  st_cast("POLYGON") %>%
  group_by(DistrictNa) %>%
  summarise(geometry = st_union(geom)) %>%
  st_sf()




request_trial <- ca_loc_sf(loc = big_sur, idfld = "DistrictNa") %>%
      ca_cvar(cvar = "tasmax") %>%
      # Historic dataset
      ca_livneh(TRUE) %>%
      ca_period("day")  %>%
      ca_years(start = 1961, end = 1990) %>% 
  ca_options(spatial_ag = "max")
    
plot(request_trial)

request_trial %>% ca_preflight()


trial_2 <- request_trial %>%
  #Get values from request
  ca_getvals_tbl(quiet = TRUE) %>%
  mutate(val = as.numeric(val)) %>%
  # Calculate 98th percentile for each district historic data
  summarize(percentile_98 = quantile(val, probs = 0.98))
  





# Plotting 

trial_2 <- data.frame()


trial_2 <- request %>%
  # Get values from request
  ca_getvals_tbl(quiet = TRUE) 
    


tmap_mode("view")

tm_shape(data_df) +
  tm_polygons()
```





```{r}


library(tmap)

tmap_mode("view")


tracts_big_sur <- tracts %>% 
  filter(tract %in% c(6053011400, 6053011502))



tm_shape(tracts) +
  tm_polygons(fill = "pink") +
  tm_shape(data_df) +
  tm_polygons(fill = "yellow")

```

