```{r, message = FALSE}
library(sf)
library(tidyverse)
library(terra)
library(leaflet)
```

Wildfire hazard potential is mapped in the dashboard as the reclassified rasters from 2023 and 2012.

### reading in data
```{r}
# read in ca wildfire data
whp_ca <- rast("/capstone/casaschools/wildfire/intermediate_layers/whp_ca.tif")

# read in reclassified whp data
whp_reclass <- rast("/capstone/casaschools/wildfire/intermediate_layers/whp_reclass.tif")

# read in archived reclassified whp data
whp_reclass2012 <- rast("/capstone/casaschools/wildfire/intermediate_layers/whp_reclass2012.tif")

# read in school buffers clipped
schools_buffers_clip <- st_read("/capstone/casaschools/schools_data/schools_buffer_clip/schools_buffer_clip.shp",
                                quiet = TRUE)

# read in full school buffers
schools_buffers <- st_read("/capstone/casaschools/schools_data/schools_buffer/schools_points_buffer.shp",
                           quiet = TRUE)
```

### mapping the 2023 whp data
```{r}
## mapping the 2023 whp data
# filter for one school
dp <- schools_buffers %>% 
  filter(SchoolName == "Dos Pueblos Senior High")

# create the school point as the centroid of the buffer
dp_point <- dp %>% 
  st_centroid()

# select the wildfire hazard potential cells that overlap
whp_school <- crop(whp_reclass, dp)
whp_school2012 <- crop(whp_reclass2012, dp)

# data needs to be in lot/long format, or transformed to WGS 1984
dp <- st_transform(dp, crs = 4326)
dp_point <- st_transform(dp_point, crs = 4326)

# define color palette and labels for wildfire hazard potential
labels <- c("developed or open water", "very low", "low", "moderate", "high", "very high", "")
whp_colors <- c("grey", "#fee391", "#fec44f", "#fe9929", "#d95f0e", "#993404", "transparent")
whp_palette <- colorFactor(palette = whp_colors,
                           domain = values(whp_school),
                           na.color = "transparent")

# mapping them together
leaflet(options = leafletOptions(
            attributionControl = FALSE)) %>% 
  
  # add topo basemap
  addProviderTiles(providers$Esri.WorldTopoMap, group = "topographic map") %>%
  
  # add imagery basemap
  addProviderTiles(providers$Esri.WorldImagery, group = "satellite imagery") %>%
  
  # add cropped wildfire hazard potential raster for 2023 
  addRasterImage(whp_school, colors = whp_palette, opacity = .7, group = "wildfire hazard 2023") %>%
  
   # add cropped wildfire hazard potential raster for 2012
  addRasterImage(whp_school2012, colors = whp_palette, opacity = .7, group = "wildfire hazard 2012") %>% 
  
  # add school buffer polygon
  addPolygons(data = dp, color = "black", fill = FALSE, 
              weight = 2, group = "school community area") %>% 
  
  # add school point
  addCircleMarkers(data = dp_point, color = "blue", stroke = FALSE, 
                   weight = 3, radius = 5, fillOpacity = 1,
                   group = "school point") %>% 
  
  # add legend for wildfire hazard potential with custom labels
  addLegend("bottomright", colors = rev(whp_colors), labels = rev(labels),
            title = "wildfire hazard potential", opacity = 1) %>% 
  
  # add a scale bar
  addScaleBar(position =  "bottomleft",
              options = scaleBarOptions(imperial = TRUE,
                                        metric = FALSE,
                                        maxWidth = 300)) %>% 
  
  # add option to toggle data on and off
  addLayersControl(
    overlayGroups = c("wildfire hazard 2023", "wildfire hazard 2012", "school community area", "school point"),
    baseGroups = c("topographic map", "satellite imagery"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  # toggle the 2012 whp data off by default
  hideGroup("wildfire hazard 2012")
  
```

```{r}
# leaflet map of wildfire hazard potential for 2012
leaflet() %>% 
  
   # add topo basemap
  addProviderTiles(providers$Esri.WorldTopoMap, group = "topographic map") %>%
  
  # add imagery basemap
  addProviderTiles(providers$Esri.WorldImagery, group = "satellite imagery") %>% 
  
  # add cropped wildfire hazard potential raster for 2023 
  addRasterImage(whp_school2012, colors = whp_palette, opacity = .7, group = "wildfire hazard potential") %>%
  
  # add school buffer polygon
  addPolygons(data = dp, color = "black", fill = FALSE, 
              weight = 2, group = "school community area") %>% 
  
  # add school point
  addCircleMarkers(data = dp_point, color = "blue", stroke = FALSE, 
                   weight = 3, radius = 5, fillOpacity = 1,
                   group = "school point") %>% 
  
   # add option to toggle data on and off
  addLayersControl(
    overlayGroups = c("wildfire hazard potential", "school community area", "school point"),
    baseGroups = c("topographic map", "satellite imagery"),
    options = layersControlOptions(collapsed = FALSE))
```
